name: Push Update

on:
  push:
    branches:
      - main

concurrency:
  group: main-update
  cancel-in-progress: false

jobs:
  update:
    name: 🛠 Push Update
    runs-on: [self-hosted, linux, arm64]
    defaults:
      run:
        working-directory: mobile
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: mobile/yarn.lock

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: ⚙️ Generate GraphQL files
        run: yarn gql

      - name: 🚀 Create update
        run: eas update --auto --non-interactive
