name: Terraform Apply

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-apply.yml"

concurrency:
  group: terraform-apply
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  determine_environment:
    name: 🏗️ Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine_environment.outputs.result }}
    steps:
      - name: 🏗 Check out the repo
        uses: actions/checkout@v6

      - name: 🧪 Determine Environment
        uses: actions/github-script@v9
        id: determine_environment
        with:
          script: |
            if ('${{ github.ref_type }}' === 'tag') {
              return 'prod';
            } else {
              return 'beta';
            }
          result-encoding: string

  tf_apply:
    name: 🏗️ Terraform Apply
    runs-on: ubuntu-latest
    needs:
      - determine_environment
    environment:
      name: ${{ needs.determine_environment.outputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
    steps:
      - name: 🏗 Check out the repo
        uses: actions/checkout@v6

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🏗 Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.0
          terraform_wrapper: true

      - name: 🏗 Terraform Init
        working-directory: terraform
        run: |
          terraform init
          terraform workspace select ${{ needs.determine_environment.outputs.environment }}

      - name: 🪄 Terraform Apply
        working-directory: terraform
        run: |
          terraform apply \
            -var-file="vars/${{ needs.determine_environment.outputs.environment }}.tfvars" \
            -var="sha=${{ github.sha }}" \
            -auto-approve
